target 'TB-Mobile-iOS' do
  
pod 'AFNetworking'
pod 'MBProgressHUD'
pod 'MJRefresh'
pod 'SDCycleScrollView'
pod 'Bugly'

use_frameworks!
pod 'JWTDecode'
pod 'Starscream'
pod 'Charts', '~> 3.0.2'

end
