target 'TB-Mobile-iOS' do
  
pod 'AFNetworking'
pod 'MBProgressHUD'
pod 'MJRefresh'
pod 'SDCycleScrollView'
pod 'Bugly'
pod 'EZUIKit'

use_frameworks!
pod 'JWTDecode'
pod 'Starscream'
pod 'Charts'



end
